apiVersion: v1
kind: Service
metadata:
  name: {{ include "remindful.fullname" . }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "remindful.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "remindful.selectorLabels" . | nindent 4 }}
