<%
  # Parse parameters out of ENV['DATABASE_URL']
  uri = URI.parse(ENV.fetch('DATABASE_URL', 'postgresql://localhost'))
  database = (uri.path || '').split('/')[1]
  username = uri.user
  password = uri.password
  host = uri.host
  port = uri.port
%>

default: &default
  adapter: postgresql
  database: <%= database %>
  username: <%= username %>
  password: "<%= password %>"
  host: <%= host %>
  port: <%= port %>

production:
  <<: *default

development:
  <<: *default
  database: remindful_server_development

test:
  <<: *default
  database: remindful_test
